version: '3.5'

services:
  db:
    image: postgres:13.11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345!!!
      - POSTGRES_PORT=5433
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    container_name: nest-js-realworld-api
    environment:
      - PORT=3003
    ports:
      - '3003:3003'
    depends_on:
      - db